In [38]:
import torch
import torch.nn as nn
from torchvision.models import vgg19, VGG19_Weights

In [61]:
vgg19(weights = VGG19_Weights.DEFAULT)

VGG(
  (features): Sequential(
    (0): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): ReLU(inplace=True)
    (2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (3): ReLU(inplace=True)
    (4): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (5): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (6): ReLU(inplace=True)
    (7): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (8): ReLU(inplace=True)
    (9): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (10): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (11): ReLU(inplace=True)
    (12): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (13): ReLU(inplace=True)
    (14): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (15): ReLU(inplace=True)
    (16): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padd

In [58]:
class NST(nn.Module):
    def __init__(self, conv_indexes = (0,5,10,19,28)):
        super().__init__()
        model = vgg19(weights = VGG19_Weights.DEFAULT)
        model = model.features[:31]
        modules = []
        layers = []
        for i, l in enumerate(model.children()):
            layers.append(l)
            if i in conv_indexes:
                print(i)
                modules.append(nn.Sequential(*layers))
                layers = []
        if len(layers) > 0:
            modules.append(nn.Sequential(*layers))

        self.modules = modules

    def forward(self, x):
        middle_outputs = []
        for m in self.modules:
            x = m(x)
            middle_outputs.append(x)
        return x, middle_outputs

In [59]:
model = NST()
x = torch.rand((1,3,256,256))
x, middle_outputs = model(x)

0
5
10
19
28


In [60]:
model.

NST()

In [50]:
x.shape

torch.Size([1, 512, 16, 16])

In [55]:
middle_outputs[0].shape

torch.Size([1, 64, 256, 256])

In [23]:
# model[0]
# model[5]
# model[10]
# model[19]
# model[28]



Parameter containing:
tensor([[[[-5.3474e-02, -4.9257e-02, -6.7942e-02],
          [ 1.5314e-02,  4.5068e-02,  2.1444e-03],
          [ 3.6226e-02,  1.9999e-02,  1.9864e-02]],

         [[ 1.7015e-02,  5.5403e-02, -6.2293e-03],
          [ 1.4165e-01,  2.2705e-01,  1.3758e-01],
          [ 1.2000e-01,  2.0030e-01,  9.2114e-02]],

         [[-4.4885e-02,  1.2680e-02, -1.4497e-02],
          [ 5.9742e-02,  1.3955e-01,  5.4102e-02],
          [-9.6141e-04,  5.8304e-02, -2.9663e-02]]],


        [[[ 2.6072e-01, -3.0489e-01, -5.0152e-01],
          [ 4.1376e-01, -2.0831e-01, -4.9086e-01],
          [ 5.8770e-01,  4.2851e-01, -1.3850e-01]],

         [[ 2.8746e-01, -3.3338e-01, -4.5564e-01],
          [ 3.7836e-01, -2.9144e-01, -4.9720e-01],
          [ 5.4778e-01,  4.8983e-01, -1.7166e-01]],

         [[ 6.7260e-02, -9.5386e-02, -3.8037e-02],
          [ 6.1955e-02, -1.3125e-01, -1.0691e-01],
          [ 4.8107e-02,  2.2999e-01, -3.0578e-02]]],


        [[[-3.2457e-02,  1.6281e-01,  5.9687

In [78]:
a = torch.Tensor([[1,2,3,4]])
b = torch.transpose(a, 0, 1)

In [79]:
a.shape, b.shape

(torch.Size([1, 4]), torch.Size([4, 1]))

In [80]:
a*b

tensor([[ 1.,  2.,  3.,  4.],
        [ 2.,  4.,  6.,  8.],
        [ 3.,  6.,  9., 12.],
        [ 4.,  8., 12., 16.]])

In [86]:
import tensorflow.keras.backend as K
import tensorflow as tf

In [99]:
def gram_matrix(x):
    features = K.batch_flatten(K.permute_dimensions(x, (2, 0, 1)))
    gram = K.dot(features, K.transpose(features))
    return gram

In [95]:
a = tf.random.uniform((10,10,3))
a.shape

TensorShape([10, 10, 3])

In [103]:
features = K.batch_flatten(K.permute_dimensions(a, (2, 0, 1)))
features.shape

TensorShape([3, 100])

In [104]:
K.transpose(features).shape

TensorShape([100, 3])

In [106]:
K.dot(tf.random.uniform((3,10)), tf.random.uniform((3,10)))

2025-11-24 15:33:55.636634: I tensorflow/core/framework/local_rendezvous.cc:407] Local rendezvous is aborting with status: INVALID_ARGUMENT: Matrix size-incompatible: In[0]: [3,10], In[1]: [3,10]


InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,10], In[1]: [3,10] [Op:MatMul] name: 

In [101]:
gram_matrix(a)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[34.404922, 25.732718, 25.352043],
       [25.732718, 31.192247, 23.154596],
       [25.352043, 23.154596, 33.679424]], dtype=float32)>

In [107]:
torch.mm(torch.randn(3,10), torch.randn(10,3))

tensor([[-0.4498, -2.4650,  5.2542],
        [ 5.5276,  0.2796,  0.7115],
        [ 1.1566, -5.0230,  0.3190]])

In [112]:
img = torch.randn(3, 5, 5)

In [114]:
img

tensor([[[ 1.2688,  0.1762,  0.6877, -0.8448,  0.0339],
         [-1.0214,  0.7966,  0.9947,  1.3992,  0.3179],
         [-2.2074, -1.6430,  1.2870,  1.6929,  2.5490],
         [ 0.3537, -0.8652,  0.4017, -1.4307,  0.3830],
         [ 0.3257, -1.1227,  1.4968,  0.3074,  2.3880]],

        [[-0.4117,  0.3034, -0.3589, -1.8563, -0.1077],
         [-0.1758,  1.1975,  1.5634, -0.1251,  0.1447],
         [-0.0989, -0.2848, -1.6312, -1.7303,  0.0737],
         [-0.7804, -0.1769,  2.4069, -1.0084,  0.3675],
         [ 0.1328, -0.4179, -1.0826,  1.7078,  0.5612]],

        [[-0.8021,  3.7106,  0.9009,  1.4615, -0.5546],
         [-0.4929,  1.6011,  1.1863,  0.2020, -0.6221],
         [ 0.2075,  0.5448, -0.5391, -0.8967, -0.4126],
         [ 2.8668,  0.0958, -1.7004, -1.1320,  0.0879],
         [-0.7266, -2.1062, -1.4791,  0.1466, -0.4040]]])

In [117]:
img[:,:-1,:] - img[:,1:,:]

tensor([[[-1.0214,  0.7966,  0.9947,  1.3992,  0.3179],
         [-2.2074, -1.6430,  1.2870,  1.6929,  2.5490],
         [ 0.3537, -0.8652,  0.4017, -1.4307,  0.3830],
         [ 0.3257, -1.1227,  1.4968,  0.3074,  2.3880]],

        [[-0.1758,  1.1975,  1.5634, -0.1251,  0.1447],
         [-0.0989, -0.2848, -1.6312, -1.7303,  0.0737],
         [-0.7804, -0.1769,  2.4069, -1.0084,  0.3675],
         [ 0.1328, -0.4179, -1.0826,  1.7078,  0.5612]],

        [[-0.4929,  1.6011,  1.1863,  0.2020, -0.6221],
         [ 0.2075,  0.5448, -0.5391, -0.8967, -0.4126],
         [ 2.8668,  0.0958, -1.7004, -1.1320,  0.0879],
         [-0.7266, -2.1062, -1.4791,  0.1466, -0.4040]]])

In [118]:
img[:,:,:-1] - img[:,:,1:]

tensor([[[ 1.0925, -0.5115,  1.5325, -0.8787],
         [-1.8179, -0.1982, -0.4045,  1.0813],
         [-0.5644, -2.9300, -0.4059, -0.8561],
         [ 1.2188, -1.2669,  1.8324, -1.8137],
         [ 1.4484, -2.6195,  1.1894, -2.0807]],

        [[-0.7150,  0.6623,  1.4974, -1.7486],
         [-1.3732, -0.3659,  1.6885, -0.2698],
         [ 0.1859,  1.3464,  0.0991, -1.8040],
         [-0.6035, -2.5837,  3.4153, -1.3759],
         [ 0.5507,  0.6647, -2.7904,  1.1466]],

        [[-4.5127,  2.8097, -0.5606,  2.0161],
         [-2.0940,  0.4148,  0.9843,  0.8241],
         [-0.3373,  1.0840,  0.3576, -0.4842],
         [ 2.7710,  1.7962, -0.5684, -1.2199],
         [ 1.3796, -0.6271, -1.6256,  0.5506]]])

In [119]:
torch.pow(img,2)

tensor([[[1.6098e+00, 3.1063e-02, 4.7293e-01, 7.1362e-01, 1.1506e-03],
         [1.0432e+00, 6.3449e-01, 9.8944e-01, 1.9578e+00, 1.0108e-01],
         [4.8727e+00, 2.6994e+00, 1.6564e+00, 2.8659e+00, 6.4975e+00],
         [1.2507e-01, 7.4856e-01, 1.6133e-01, 2.0469e+00, 1.4665e-01],
         [1.0608e-01, 1.2604e+00, 2.2404e+00, 9.4466e-02, 5.7026e+00]],

        [[1.6946e-01, 9.2025e-02, 1.2882e-01, 3.4458e+00, 1.1595e-02],
         [3.0893e-02, 1.4340e+00, 2.4441e+00, 1.5659e-02, 2.0940e-02],
         [9.7770e-03, 8.1118e-02, 2.6609e+00, 2.9941e+00, 5.4280e-03],
         [6.0895e-01, 3.1277e-02, 5.7930e+00, 1.0169e+00, 1.3506e-01],
         [1.7636e-02, 1.7463e-01, 1.1720e+00, 2.9167e+00, 3.1495e-01]],

        [[6.4336e-01, 1.3768e+01, 8.1156e-01, 2.1360e+00, 3.0761e-01],
         [2.4295e-01, 2.5635e+00, 1.4072e+00, 4.0805e-02, 3.8697e-01],
         [4.3050e-02, 2.9683e-01, 2.9066e-01, 8.0412e-01, 1.7022e-01],
         [8.2188e+00, 9.1783e-03, 2.8915e+00, 1.2814e+00, 7.7287e-03],
  

In [122]:
1.2688**2

1.6098534399999997