In [37]:
import torch

In [53]:
a = torch.tensor([[.10,.20,.35],[.10,.20,.30]], requires_grad=True)

In [54]:
a

tensor([[0.1000, 0.2000, 0.3500],
        [0.1000, 0.2000, 0.3000]], requires_grad=True)

In [55]:
a.sum(dim=1)

tensor([0.6500, 0.6000], grad_fn=<SumBackward1>)

In [56]:
a = torch.tensor([1,2,3,4,5,6,6])

In [65]:
a[-3:]

tensor([5, 6, 6])